baseURL = "https://pengantar.github.io/midu.dev/"
languageCode = "es-ES"
title = "midudev 👨‍💻 | Frontend, Javascript, React, CSS, Performance"

disableHugoGeneratorInject = true
defaultContentLanguage = "es"
preserveTaxonomyNames = true
paginate = 10

[permalinks]
  posts = "/:filename/"

[params]
  description = "Artículos, vídeos, recursos y tutoriales sobre Desarrollo Web, Frontend, Javascript ☕️, React ⚛️, CSS 🎨 y Performance Web ⚡️"
  image = "/favicon/apple-touch-icon.png"

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats]
  [outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true
